### ISSUE TITLE
Cannot provision TLS certificate

### ISSUE THREAD

**Issue by migandhi** [ddavness/power-mailinabox#142]
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/usr/lib/python3/dist-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/usr/lib/python3/dist-packages/josepy/interfaces.py", line 7, in <module>
    from josepy import errors, util
  File "/usr/lib/python3/dist-packages/josepy/util.py", line 7, in <module>
    import OpenSSL
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 35, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 963, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by migandhi** [comment]
Hi,
Greetings,

I found solution to the issue
It was the problems with certbot
I installed new package manager snapd
Using snap I had to install certbot with --classic flag
This may have done the trick
I got this error resolved
I got guidance from certbot website
https://certbot.eff.org/

Regards.
