### ISSUE TITLE
TLS/SSL Certificate generation failed.

### ISSUE THREAD

**Issue by gkbaby** [ddavness/power-mailinabox#35]
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1382, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1249, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 607, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 515, in _determine_account
    acc = display_ops.choose_account(accounts)
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 84, in choose_account
    code, index = z_util(interfaces.IDisplay).menu(
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 503, in menu
    self._interaction_fail(message, cli_flag, "Choices: " + repr(choices))
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 466, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Please choose an account
Choices: ['mydomainname@2021-04-27T16:55:59Z (88ac)', 'mydomainname@2021-09-07T17:48:33Z (b80e)']
```
Hi, My box which runs the latest version v0.54.POWER.5 ran into this issue. running sudo mailinabox didnt fix the issue - but i was able to login to the admin dashboard after that using http which was blocked by htst protocol earlier.

**Comment by gkbaby** [comment]
I followed this [thread](https://community.letsencrypt.org/t/please-choose-an-account/17262/2) and deleted the old account and the provisioning of Cert from UI worked fine.

**Comment by gkbaby** [comment]
The old account was present in the directory /home/user-data/ssl/lets_encrypt/accounts/acme-v02.api.letsencrypt.org/directory. 
Is this an issue with Mailinabox's certbot script?
