### ISSUE TITLE
0.60 upgrade giving me multiple duplicity errors? 

### ISSUE THREAD

**Issue by mannp** [ddavness/power-mailinabox#81]
Any help as to the solution would be much appreciated, thanks.

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

```
FAILED: pip3 install --upgrade b2sdk boto3 duplicity
-----------------------------------------
Requirement already satisfied: b2sdk in /usr/local/lib/python3.9/dist-packages (1.7.0)
Collecting b2sdk
  Using cached b2sdk-1.18.0.tar.gz (313 kB)
Collecting boto3
  Using cached boto3-1.24.91-py3-none-any.whl (132 kB)
Collecting duplicity
  Using cached duplicity-1.0.1.tar.gz (1.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jma43xlf/duplicity_76917fc45078487dbdd318fe19cc6a58/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jma43xlf/duplicity_76917fc45078487dbdd318fe19cc6a58/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1r63wvv7
         cwd: /tmp/pip-install-jma43xlf/duplicity_76917fc45078487dbdd318fe19cc6a58/
    Complete output (9 lines):
    sh: 1: msgfmt: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jma43xlf/duplicity_76917fc45078487dbdd318fe19cc6a58/setup.py", line 303, in <module>
        data_files=get_data_files(),
      File "/tmp/pip-install-jma43xlf/duplicity_76917fc45078487dbdd318fe19cc6a58/setup.py", line 124, in get_data_files
        assert not os.system(u"msgfmt po/%s.po -o po/%s/duplicity.mo" % (lang, lang)), lang
    AssertionError: bg
    Unable to get SCM version: defaulting to 1.0.1
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/3c/cc12cf3e2b193583d76b2bbccd7d3b74cc67b393de3494c26dcd741310f4/duplicity-1.0.1.tar.gz#sha256=24b4d8af0d167d0498c3c9d7ce4151db08f6b3175a3e295eeccfe42915b1fe90 (from https://pypi.org/simple/duplicity/) (requires-python:>2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached duplicity-1.0.0.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jma43xlf/duplicity_1656429b3c7a46de880c6b26571fc8aa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jma43xlf/duplicity_1656429b3c7a46de880c6b26571fc8aa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qmg9ubp0
         cwd: /tmp/pip-install-jma43xlf/duplicity_1656429b3c7a46de880c6b26571fc8aa/
    Complete output (9 lines):
    sh: 1: msgfmt: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jma43xlf/duplicity_1656429b3c7a46de880c6b26571fc8aa/setup.py", line 303, in <module>
        data_files=get_data_files(),
      File "/tmp/pip-install-jma43xlf/duplicity_1656429b3c7a46de880c6b26571fc8aa/setup.py", line 124, in get_data_files
        assert not os.system(u"msgfmt po/%s.po -o po/%s/duplicity.mo" % (lang, lang)), lang
    AssertionError: bg
    Unable to get SCM version: defaulting to 1.0.0
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/8e/925915ebb527df5fe91d17af37637939ffe476ce088f194d74cd99567bc6/duplicity-1.0.0.tar.gz#sha256=bd3c8a5ad3cf9d2709540806b03d7186f9e4473d922bea6051248a2acc7ecf0f (from https://pypi.org/simple/duplicity/) (requires-python:>2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached duplicity-0.8.23.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jma43xlf/duplicity_04d9a214875540cd8c19d21baebcfc3b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jma43xlf/duplicity_04d9a214875540cd8c19d21baebcfc3b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-20vbi7uv
         cwd: /tmp/pip-install-jma43xlf/duplicity_04d9a214875540cd8c19d21baebcfc3b/
    Complete output (9 lines):
    sh: 1: msgfmt: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jma43xlf/duplicity_04d9a214875540cd8c19d21baebcfc3b/setup.py", line 303, in <module>
        data_files=get_data_files(),
      File "/tmp/pip-install-jma43xlf/duplicity_04d9a214875540cd8c19d21baebcfc3b/setup.py", line 124, in get_data_files
        assert not os.system(u"msgfmt po/%s.po -o po/%s/duplicity.mo" % (lang, lang)), lang
    AssertionError: bg
    Unable to get SCM version: defaulting to 0.8.23
    ----------------------------------------

```
```
  Downloading duplicity-0.8.11.1566.tar.gz (644 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/80/72/c018fe95cb127cc2cfde496a69a3fea639daddf8ff7f3cea0e0fc1a73119/duplicity-0.8.11.1566.tar.gz#sha256=5920a4afab9cec3534f799d9f8ba505f1cc296e0b212527a3430a34e801a386a (from https://pypi.org/simple/duplicity/) (requires-python:>2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, <4). Requested duplicity from https://files.pythonhosted.org/packages/80/72/c018fe95cb127cc2cfde496a69a3fea639daddf8ff7f3cea0e0fc1a73119/duplicity-0.8.11.1566.tar.gz#sha256=5920a4afab9cec3534f799d9f8ba505f1cc296e0b212527a3430a34e801a386a has different version in metadata: '0.8.11.0'
ERROR: Could not find a version that satisfies the requirement duplicity
ERROR: No matching distribution found for duplicity
```

**Comment by ddavness** [comment]
Alright, according to the logs, it seems that the package `msgfmt` needs to be installed and it is not.
This can happen since we don't explicitly install this during setup either, should be fixed on the next release hopefully.

**Comment by mannp** [comment]
> Alright, according to the logs, it seems that the package `msgfmt` needs to be installed and it is not. This can happen since we don't explicitly install this during setup either, should be fixed on the next release hopefully.

Great thanks ... is that installed via pip or apt? Thx

**Comment by ddavness** [comment]
Via apt

**Comment by mannp** [comment]
> Via apt

Installed gettext and everything went through fine.

**Comment by ddavness** [comment]
`msgfmt` comes with `gettext` so that checks out
